-- First, clear existing stories for sample memorials
DELETE FROM stories WHERE memorial_id IN (
  SELECT id FROM memorials WHERE id LIKE 'sample-%'
);

-- Add realistic reviews with dates ranging back to 2017
INSERT INTO stories (memorial_id, author_name, content, created_at, is_approved) VALUES
-- For sample-1 (Robert James Anderson)
('sample-1', 'Margaret Wilson', 'Robert was my colleague for over 20 years at Pacific Northwest Engineering. His mentorship shaped my career and his kindness touched everyone he met. I still use the wooden pen holder he crafted for me when I got promoted. His legacy lives on in all the engineers he trained.', '2017-03-15T14:23:00Z', true),
('sample-1', 'Thomas Jenkins', 'I served with Robert in Vietnam. We kept in touch all these years, and I''ll never forget his courage under fire and his unwavering loyalty to his fellow soldiers. When my son was interested in engineering, Robert spent an entire weekend showing him around his workshop and explaining the principles. That''s the kind of man he was.', '2018-07-22T10:15:00Z', true),
('sample-1', 'Sarah Rodriguez', 'Uncle Robert was the one who taught me how to fish when I was just 8 years old. He had endless patience and always made time for family. I remember how proud he was when I caught my first trout. Those summer fishing trips are memories I''ll cherish forever.', '2019-11-05T16:42:00Z', true),
('sample-1', 'David Chen', 'As Robert''s neighbor for 15 years, I witnessed his generosity countless times. From helping me rebuild my deck to organizing the neighborhood watch program, he was always the first to volunteer. The community hasn''t been the same without his leadership and warm smile.', '2021-04-18T09:30:00Z', true),
('sample-1', 'Emily Johnson', 'Mr. Anderson volunteered at our school''s woodworking club for years. My son still has the birdhouse they built together. Robert had a special way of connecting with children and teaching them not just skills, but values. We miss him dearly at Lincoln Elementary.', '2022-09-30T13:45:00Z', true),

-- For sample-2 (Elizabeth Marie Thompson)
('sample-2', 'Michael Peterson', 'Mrs. Thompson was my English teacher in 1985, and she changed my life. Her passion for literature inspired me to become a writer. When my first novel was published in 2010, she was there at the book signing, beaming with pride. I owe my career to her belief in me.', '2017-06-10T11:20:00Z', true),
('sample-2', 'Jennifer Adams', 'Elizabeth was my mentor when I started teaching. Her innovative methods and deep care for each student set the standard I still aspire to meet. She taught me that teaching is about touching lives, not just covering curriculum. Her influence extends through generations of educators she trained.', '2018-09-28T15:35:00Z', true),
('sample-2', 'Robert Thompson', 'My beloved mother had a gift for finding beauty in everyday moments. She could turn a simple family dinner into a celebration, and her home was always open to anyone who needed comfort. Her wisdom guides me daily as I raise my own children.', '2020-02-14T10:05:00Z', true),
('sample-2', 'Susan Miller', 'Elizabeth led our community book club for over 30 years. Her insights into literature were profound, but what I''ll remember most is how she made everyone feel valued and heard. She had a way of drawing out even the quietest members and celebrating diverse perspectives.', '2021-08-03T16:15:00Z', true),
('sample-2', 'James Wilson', 'As the principal who worked alongside Elizabeth for 15 years, I witnessed her extraordinary impact on countless students. She fought tirelessly for resources for underprivileged children and stayed after hours to tutor those who needed extra help. Her legacy is in the success stories of students who might otherwise have been left behind.', '2023-01-25T14:40:00Z', true),

-- For sample-3 (Michael David Wilson)
('sample-3', 'Patricia Garcia', 'Michael gave me my first job when no one else would take a chance on me. His mentorship helped me grow from an entry-level position to eventually starting my own business. He taught me that integrity and hard work are the foundations of success. I wouldn''t be where I am today without his guidance.', '2017-11-12T09:15:00Z', true),
('sample-3', 'Richard Wilson', 'Dad was the most generous person I''ve ever known. He anonymously paid college tuition for dozens of local students and never wanted recognition. His philosophy was that success is measured by the lives you touch, not the wealth you accumulate. I strive to honor his legacy through my own charitable work.', '2018-04-30T13:25:00Z', true),
('sample-3', 'Linda Martinez', 'As Michael''s business partner for over 20 years, I witnessed his exceptional leadership daily. During the 2008 recession, he took a pay cut himself rather than lay off employees. His integrity and compassion built a company culture that felt like family. The business community has lost a true visionary.', '2019-10-15T11:50:00Z', true),
('sample-3', 'William Johnson', 'Michael was my Little League coach when I was 10. He taught us that winning wasn''t as important as playing with heart and supporting teammates. Those lessons shaped my character far beyond baseball. Decades later, he still remembered my name and asked about my family whenever we met.', '2020-07-08T16:30:00Z', true),
('sample-3', 'Karen Taylor', 'Michael led our Chamber of Commerce through a period of tremendous growth. His innovative ideas brought new businesses to our struggling downtown and created hundreds of jobs. Beyond his business acumen, he was known for his infectious laugh and ability to find common ground with anyone. Our community was blessed to have him.', '2021-11-28T10:45:00Z', true);
